spring:
  datasource:
    url: jdbc:mysql://prod-db:3306/productdb
    username: prod_user
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration/mysql
  sql:
    init:
      mode: never
logging:
  level:
    root: WARN
