spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:productdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false
  sql:
    init:
      mode: always

jwt:
  secret: 0123456789ABCDEF0123456789ABCDEF
logging:
  level:
    root: INFO

# Note:
# - Default profile uses in-memory H2 so the app runs without external DB.
# - For MySQL, use: -Dspring.profiles.active=dev and ensure MySQL is running.

springdoc:
  swagger-ui:
    path: /swagger-ui.html
