spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: "Mivada@123"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # Let Flyway handle schema
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/mysql
    baseline-on-migrate: true
  sql:
    init:
      mode: never

logging:
  level:
    root: DEBUG
